# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residentialname', models.CharField(max_length=30)),
                ('workaddress', models.CharField(max_length=30)),
                ('businessemail', models.EmailField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Bankers_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('account_name', models.PositiveIntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lifeassured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('agelastbirthday', models.CharField(max_length=30)),
                ('maritalstatus', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupationname', models.CharField(max_length=30)),
                ('annualincome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='premiumpaymethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(upload_to='profile/')),
                ('maritalstatus', models.CharField(max_length=30)),
                ('cellphone', models.IntegerField()),
                ('emailaddress', models.EmailField(max_length=75)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('dateofbirth', models.DateTimeField()),
                ('id_number', models.IntegerField()),
                ('maritalstatus', models.CharField(max_length=30)),
                ('cellphone', models.IntegerField()),
                ('emailaddress', models.EmailField(max_length=75)),
                ('relationshiptoassured', models.CharField(max_length=30)),
            ],
        ),
    ]
