# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimaapp', '0002_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AddField(
            model_name='bankers_order',
            name='bank_name',
            field=models.CharField(choices=[('Equity Bank', 'Equity Bank'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('Kenya Commercial Bank', 'Kenya Commercial Bank'), ('Barclays', 'Barclays')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumpaymethod',
            name='paymethod',
            field=models.CharField(choices=[('Mpesa Paybill', 'Mpesa Paybill'), ('Cheque Payments', 'Cheque Payments'), ('Check-off', 'Check-off'), ('Direct Debit', 'Direct Debit')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
