# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimaapp', '0003_auto_20181026_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maritalstatus',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
