# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimaapp', '0004_auto_20181026_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankers_order',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankers_order',
            name='account_number',
            field=models.PositiveIntegerField(),
        ),
    ]
